# The map of all api type for templates
TEMPLATE_TYPE={
    'unmasked contiguous load':                        'template_head.c',
    'CSR Register Configure: CSR Read':                'template_head.c',
    'CSR Register Configure: CSR Scalar Write':        'template_head.c',
    'CSR Register Configure: CSR immediate Write':     'template_head.c',
    'Contiguous Load: Unmasked Load':                  'template_head.c',
    'Contiguous Load: Masked Load':                    'template_head.c',
    'Contiguous Store: Unmasked Store':                'template_head.c',
    'Contiguous Store: Masked Store':                  'template_head.c',
    'Interleave Load: Unmasked Load':                  'template_head.c',
    'Interleave Load: Masked Load':                    'template_head.c',
    'Interleave Store: Unmasked Store':                'template_head.c',
    'Interleave Store: Masked Store':                  'template_head.c',
    'Indexed Load: Unmasked Load':                     'template_head.c',
    'Indexed Load: Masked Load':                       'template_head.c',
    'Indexed Store: Unmasked Store':                   'template_head.c',
    'Indexed Store: Masked Store':                     'template_head.c',
    'Arithmetic: Unmasked Add':                        'template_head.c',
    'Arithmetic: Masked Add':                          'template_head.c',
    'Arithmetic: Unmasked Sub':                        'template_head.c',
    'Arithmetic: Masked Sub':                          'template_head.c',
    'Arithmetic: Unmasked Multiply':                   'template_head.c',
    'Arithmetic: Masked Multiply':                     'template_head.c',
    'Arithmetic: Unmasked Neg':                        'template_head.c',
    'Arithmetic: Masked Neg':                          'template_head.c',
    'Arithmetic: Unmasked Min':                        'template_head.c',
    'Arithmetic: Masked Min':                          'template_head.c',
    'Arithmetic: Unmasked Max':                        'template_head.c',
    'Arithmetic: Masked Max':                          'template_head.c',
    'Logic: Unmasked Vector logical':                  'template_head.c',
    'Logic: Masked Vector logical':                    'template_head.c',
    'Logic: Unmasked Mask logical':                    'template_head.c',
    'Logic: Masked Mask logical':                      'template_head.c',
    'Shift: Unmasked Logic Shift Left':                'template_head.c',
    'Shift: Masked Logic Shift Left':                  'template_head.c',
    'Shift: Unmasked Logic Shift Right':               'template_head.c',
    'Shift: Masked Logic Shift Right':                 'template_head.c',
    'Shift: Unmasked Arithmetic Shift Right':          'template_head.c',
    'Shift: Masked Arithmetic Shift Right':            'template_head.c',
    'Shift: Unmasked Accumulator Shift Right':         'template_head.c',
    'Shift: Masked Accumulator Shift Right':           'template_head.c',
    'Shift: Unmasked Circular Buffer Shift Left':      'template_head.c',
    'Shift: Masked Circular Buffer Shift Left':        'template_head.c',
    'Shift: Unmasked Circular Buffer Shift Right':     'template_head.c',
    'Shift: Masked Circular Buffer Shift Right':       'template_head.c',
    'Shift: Mask Shift Left':                          'template_head.c',
    'Mac: Unmasked Multiply-Add':                      'template_head.c',
    'Mac: Masked Multiply-Add':                        'template_head.c',
    'Mac: Unmasked Multiply-Subtract':                 'template_head.c',
    'Mac: Masked Multiply-Subtract':                   'template_head.c',
    'Mac: Unmasked Multiply-Neg-Add':                  'template_head.c',
    'Mac: Masked Multiply-Neg-Add':                    'template_head.c',
    'Mac: Unmasked Multiply-Neg-Subtract':             'template_head.c',
    'Mac: Masked Multiply-Neg-Subtract':               'template_head.c',
    'Reduction: Unmasked Reduce Sum':                  'template_head.c',
    'Reduction: Masked Reduce Sum':                    'template_head.c',
    'Reduction: Unmasked Reduce Dot':                  'template_head.c',
    'Reduction: Masked Reduce Dot':                    'template_head.c',
    'Reduction: Unmasked Reduce Min':                  'template_head.c',
    'Reduction: Masked Reduce Min':                    'template_head.c',
    'Reduction: Unmasked Reduce Max':                  'template_head.c',
    'Reduction: Masked Reduce Min':                    'template_head.c',
    'Move: Unmasked Duplicate':                        'template_head.c',
    'Move: Masked Duplicate':                          'template_head.c',
    'Move: Unmasked Extract':                          'template_head.c',
    'Move: Masked Extract':                            'template_head.c',
    'Move: Masket Intrinsic':                          'template_head.c',
    'Permutation: Unmasked Gather Intrinsic':          'template_head.c',
    'Permutation: Masked Gather Intrinsic':            'template_head.c',
    'Permutation: Merge Intrinsic':                    'template_head.c',
    'Conversion: Unmasked Extend Intrinsic':           'template_head.c',
    'Conversion: Masked Extend Intrinsic':             'template_head.c',
    'Conversion: Unmasked Truncate Intrinsic':         'template_head.c',
    'Conversion: Masked Truncate Intrinsic':           'template_head.c',
    'Conversion: Unmasked Clip Intrinsic':             'template_head.c',
    'Conversion: Masked Clip Intrinsic':               'template_head.c',
    'Compare: Unmasked EQ Intrinsic':                  'template_head.c',
    'Compare: Masked EQ Intrinsic':                    'template_head.c',
    'Compare: Unmasked NE Intrinsic':                  'template_head.c',
    'Compare: masked NE Intrinsic':                    'template_head.c',
    'Compare: Unmasked LT Intrinsic':                  'template_head.c',
    'Compare: Masked LT Intrinsic':                    'template_head.c',
    'Compare: Unmasked LE Intrinsic':                  'template_head.c',
    'Compare: Masked LE Intrinsic':                    'template_head.c',
    'Compare: Unmasked GT Intrinsic':                  'template_head.c',
    'Compare: Masked GT Intrinsic':                    'template_head.c',
    'Compare: Unmasked GE Intrinsic':                  'template_head.c',
    'Compare: Masked GE Intrinsic':                    'template_head.c',
    'IIR: Signed Fract Clear Dotiir':                  'template_head.c',
    'IIR: Signed Fract Dotiir':                        'template_head.c',
    'IIR: Unsigned Fract Clear Dotiir':                'template_head.c',
    'IIR: Unsigned Fract Dotiir':                      'template_head.c',
}