INTRINSIC_TYPE_MAP={
'CSR Register Configure: CSR Read'              :'vrd_csr$',
'CSR Register Configure: CSR Scalar Write'      :'vwr_csr$',
'CSR Register Configure: CSR immediate Write'   :'vwr_csri$',
'Contiguous Load: Unmasked Load'                :'vldcb[1-8]in0_v_[iu][136][624]$',
'Contiguous Load: Masked Load'                  :'vldcb[1-8]in0_v_[iu][136][624]_m$',
'Contiguous Store: Unmasked Store'              :'vstcb[1-8]in0_v_[iu][136][624]$',
'Contiguous Store: Masked Store'                :'vstcb[1-8]in0_v_[iu][136][624]_m$',
'Interleave Load: Unmasked Load'                :'vldcb[1-8]in1_v_[iu][136][624]$',
'Interleave Load: Masked Load'                  :'vldcb[1-8]in1_v_[iu][136][624]_m$',
'Interleave Store: Unmasked Store'              :'vstcb[1-8]in1_v_[iu][136][624]$',
'Interleave Store: Masked Store'                :'vstcb[1-8]in1_v_[iu][136][624]_m$',
'Indexed Load: Unmasked Load'                   :'vgldcb[1-8]_v_[iu][136][624]$',
'Indexed Load: Masked Load'                     :'vgldcb[1-8]_v_[iu][136][624]_m$',
'Indexed Store: Unmasked Store'                 :'vsstcb[1-8]_v_[iu][136][624]$',
'Indexed Store: Masked Store'                   :'vsstcb[1-8]_v_[iu][136][624]_m$',
'Arithmetic: Unmasked Add'                      :'vw?s?add_[vw][vxw]_[iu][136][624]$',
'Arithmetic: Masked Add'                        :'vw?s?add_[vw][vxw]_[iu][136][624]_m$',
'Arithmetic: Unmasked Sub'                      :'vw?s?sub_[vw][vxw]_[iu][136][624]$',
'Arithmetic: Masked Sub'                        :'vw?s?sub_[vw][vxw]_[iu][136][624]_m$',
'Arithmetic: Unmasked Multiply'                 :'vw?s?mulh?q?_v[vx]_[iu][13][62]$',
'Arithmetic: Masked Multiply'                   :'vw?s?mulh?q?_v[vx]_[iu][13][62]_m$',
'Arithmetic: Unmasked Neg'                      :'vs?neg_v_[iu][13][62]$',
'Arithmetic: Masked Neg'                        :'vs?neg_v_[iu][13][62]_m$',
'Arithmetic: Unmasked Min'                      :'vmin_v[vx]_[iu][13][62]$',
'Arithmetic: Masked Min'                        :'vmin_v[vx]_[iu][13][62]_m$',
'Arithmetic: Unmasked Max'                      :'vmax_v[vx]_[iu][13][62]$',
'Arithmetic: Masked Max'                        :'vmax_v[vx]_[iu][13][62]_m$',
'Logic: Unmasked Vector logical'                :'v(and)?(or)?(xor)?(not)?_v[vx]?_[iu][13][62]$',
'Logic: Masked Vector logical'                  :'v(and)?(or)?(xor)?(not)?_v[vx]?_[iu][13][62]_m$',
'Logic: Unmasked Mask logical'                  :'vmx?n?(or)?(and)?(not)?_mm_bool[813][62]?$',
'Logic: Masked Mask logical'                    :'vmx?n?(or)?(and)?(not)?_mm_bool[813][62]?_m$',
'Shift: Unmasked Logic Shift Left'              :'vw?s?sll_[vw][vxiw]_[iu][136][624]$',
'Shift: Masked Logic Shift Left'                :'vw?s?sll_[vw][vxiw]_[iu][136][624]_m$',
'Shift: Unmasked Logic Shift Right'             :'vw?srl_[vw][vxiw]_u[136][624]$',
'Shift: Masked Logic Shift Right'               :'vw?srl_[vw][vxiw]_u[136][624]_m$',
'Shift: Unmasked Arithmetic Shift Right'        :'vw?sra_[vw][vxiw]_i[136][624]$',
'Shift: Masked Arithmetic Shift Right'          :'vw?sra_[vw][vxiw]_i[136][624]_m$',
'Shift: Unmasked Accumulator Shift Right'       :'vwsrl_a[vxis]_[iu]64$',
'Shift: Masked Accumulator Shift Right'         :'vwsrl_a[vxis]_[iu]64_m$',
'Shift: Unmasked Circular Buffer Shift Left'    :'vcsl_i_[iu][136][624]$',
'Shift: Masked Circular Buffer Shift Left'      :'vcsl_i_[iu][136][624]_m$',
'Shift: Unmasked Circular Buffer Shift Right'   :'vcsr_i_[iu][136][624]$',
'Shift: Masked Circular Buffer Shift Right'     :'vcsr_i_[iu][136][624]_m$',
'Shift: Mask Shift Left'                        :'vmsll_mi_bool[813][62]?$',
'Shift: Mask Shift Right'                       :'vmsrl_mi_bool[813][62]?$',
'Mac: Unmasked  Multiply-Add'                   :'vw?s?maccq?_vv_[iu][13][62]_?h?l?p?$',
'Mac: Masked  Multiply-Add'                     :'vw?s?maccq?_vv_[iu][13][62]_?h?l?p?_m$',
'Mac: Unmasked  Multiply-Subtract'              :'vw?s?msubq?_vv_[iu][13][62]_?h?l?p?$',
'Mac: Masked  Multiply-Subtract'                :'vw?s?msubq?_vv_[iu][13][62]_?h?l?p?_m$',
'Mac: Unmasked  Multiply-Neg-Add'               :'vw?s?nmsacq?_vv_[iu][13][62]_?h?l?p?$',
'Mac: Masked  Multiply-Neg-Add'                 :'vw?s?nmsacq?_vv_[iu][13][62]_?h?l?p?_m$',
'Mac: Unmasked  Multiply-Neg-Subtract'          :'vw?s?nmsubq?_vv_[iu][13][62]_?h?l?p?$',
'Mac: Masked  Multiply-Neg-Subtract'            :'vw?s?nmsubq?_vv_[iu][13][62]_?h?l?p?_m$',
'Reduction: Unmasked Reduce Sum'                :'vrs?sum_v_[iu][136][624]$',
'Reduction: Masked Reduce Sum'                  :'vrs?sum_v_[iu][136][624]_m$',
'Reduction: Unmasked Reduce Dot'                :'vs?a?rdotp?(acc)?q?_vv_[iu][13][62]_?h?l?p?$',
'Reduction: Masked Reduce Dot'                  :'vs?a?rdotp?(acc)?q?_vv_[iu][13][62]_?h?l?p?_m1?$',
'Reduction: Unmasked Reduce Min'                :'vrmin_v_[iu][13][62]$',
'Reduction: Masked Reduce Min'                  :'vrmin_v_[iu][13][62]_m$',
'Reduction: Unmasked Reduce Max'                :'vrmax_v_[iu][13][62]$',
'Reduction: Masked Reduce Max'                  :'vrmax_v_[iu][13][62]_m$',
'Move: Unmasked Duplicate'                      :'vmv_v_[xi]_[iu][136][624]$',
'Move: Masked Duplicate'                        :'vmv_v_[xi]_[iu][136][624]_m$',
'Move: Unmasked Extract'                        :'vmv_x_v_[iu][13][62]$',
'Move: Masked Extract'                          :'vmv_x_v_[iu][13][62]_m$',
'Move: Masket Intrinsic'                        :'vmsetult_xx_bool[813][62]?$',
'Permutation: Unmasked Gather Intrinsic'        :'vgather_vv_[iu][13][62]$',
'Permutation: Masked Gather Intrinsic'          :'vgather_vv_[iu][13][62]_m$',
'Permutation: Merge Intrinsic'                  :'vmerge_vv_[iu][13][62]_m$',
'Conversion: Unmasked Extend Intrinsic'         :'vextend_v_[iu][13][62]$',
'Conversion: Masked Extend Intrinsic'           :'vextend_v_[iu][13][62]_m$',
'Conversion: Unmasked Truncate Intrinsic'       :'vtrunc_w_[iu][13][62]$',
'Conversion: Masked Truncate Intrinsic'         :'vtrunc_w_[iu][13][62]_m$',
'Conversion: Unmasked Clip Intrinsic'           :'vclip_wv_[iu][13][62]$',
'Conversion: Masked Clip Intrinsic'             :'vclip_wv_[iu][13][62]_m$',
'Compare: Unmasked EQ Intrinsic'                :'vcmpeq_v[vx]_[iu][13][62]$',
'Compare: Masked EQ Intrinsic'                  :'vcmpeq_v[vx]_[iu][13][62]_m$',
'Compare: Unmasked NE Intrinsic'                :'vcmpne_v[vx]_[iu][13][62]$',
'Compare: masked NE Intrinsic'                  :'vcmpne_v[vx]_[iu][13][62]_m$',
'Compare: Unmasked LT Intrinsic'                :'vcmplt_v[vx]_[iu][13][62]$',
'Compare: Masked LT Intrinsic'                  :'vcmplt_v[vx]_[iu][13][62]_m$',
'Compare: Unmasked LE Intrinsic'                :'vcmple_v[vx]_[iu][13][62]$',
'Compare: Masked LE Intrinsic'                  :'vcmple_v[vx]_[iu][13][62]_m$',
'Compare: Unmasked GT Intrinsic'                :'vcmpgt_v[vx]_[iu][13][62]$',
'Compare: Masked GT Intrinsic'                  :'vcmpgt_v[vx]_[iu][13][62]_m$',
'Compare: Unmasked GE Intrinsic'                :'vcmpge_v[vx]_[iu][13][62]$',
'Compare: Masked GE Intrinsic'                  :'vcmpge_v[vx]_[iu][13][62]_m$',
'IIR: Signed Fract Clear Dotiir'                :'vsrdotiircq_v_i32_d[1-8]s[1-8]$',
'IIR: Signed Fract Dotiir'                      :'vsrdotiirq_v_i32_d[1-8]s[1-8]$',
'IIR: Unsigned Fract Clear Dotiir'              :'vsrdotiircu_v_i32_d[1-8]s[1-8]$' ,
'IIR: Unsigned Fract Dotiir'                    :'vsrdotiiru_v_i32_d[1-8]s[1-8]$',
}


